--- 
- gather_facts: false
  hosts: all
  remote_user: root
  tasks: 

  - name: Update and upgrade packages
    become: true
    apt:
      upgrade: dist
      update_cache: yes

  - name: Install base packages
    become: true
    package:
      name: "{{ item }}"
      state: present
    with_items:
    - apt-transport-https
    - make
    - software-properties-common
    - ufw
    - unzip

  - name: NGINX - Install nginx
    become: true
    package:
      name: nginx
      state: present

  - name: NGINX - Create sites-available & sites-enabled directories
    become: true
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0755
    with_items:
      - /etc/nginx/sites-available/
      - /etc/nginx/sites-enabled/

  - name: PHP - Add repository key
    become: true
    apt_key:
      url: "https://packages.sury.org/php/apt.gpg"
      state: present

  - name: PHP - Add repository
    become: true
    shell: echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list

  - name: PHP - Update and upgrade packages
    become: true
    apt:
      upgrade: dist
      update_cache: yes

  - name: PHP - Install
    become: true
    package:
      name: "{{ item }}"
      state: present
    with_items:
    - php7.1-cli
    - php7.1-common
    - php7.1-curl
    - php7.1-dev
    - php7.1-fpm
    - php7.1-gd
    - php7.1-mbstring
    - php7.1-mcrypt
    - php7.1-opcache
    - php7.1-xml
    - php7.1-xmlrpc
    - php7.1-zip
    - php-apcu
    - php-pear
    - libyaml-dev

  - name: PHP - Install YAML parser
    become: true
    pear: 
      name: yaml-2.0.0 
      state: present

  - name: PHP - Set php.ini cgi.fix_pathinfo=0
    become: true
    replace:
      path: /etc/php/7.1/fpm/php.ini
      regexp: '(\s+)\;cgi\.fix_pathinfo\=1(\s+.*)?$'
      replace: '\1cgi.fix_pathinfo=0\2'

  - name: PHP - Set php.ini opcache.memory_consumption=128
    become: true
    replace:
      path: /etc/php/7.1/fpm/php.ini
      regexp: '(\s+)\;opcache\.memory_consumption\=128(\s+.*)?$'
      replace: '\1opcache.memory_consumption=128\2'

  - name: PHP - Set php.ini opcache.interred_strings_buffer=16
    become: true
    replace:
      path: /etc/php/7.1/fpm/php.ini
      regexp: '(\s+)\;opcache\.interned_strings_buffer\=8(\s+.*)?$'
      replace: '\1opcache.interned_strings_buffer=16\2'

  - name: PHP - Set php.ini opcache.max_accelerated_files=10000
    become: true
    replace:
      path: /etc/php/7.1/fpm/php.ini
      regexp: '(\s+)\;opcache\.max_accelerated_files\=10000(\s+.*)?$'
      replace: '\1opcache.max_accelerated_files=10000\2'

  - name: PHP - Set php.ini opcache.revalidate_freq=60
    become: true
    replace:
      path: /etc/php/7.1/fpm/php.ini
      regexp: '(\s+)\;opcache\.revalidate_freq\=2(\s+.*)?$'
      replace: '\1opcache.revalidate_freq=60\2'

  - name: PHP - Set php.ini opcache.fast_shutdown=1
    become: true
    replace:
      path: /etc/php/7.1/fpm/php.ini
      regexp: '(\s+)\;opcache\.fast_shutdown\=0(\s+.*)?$'
      replace: '\1opcache.fast_shutdown=1\2'

  - name: PHP - Add extension=yaml.so to php.ini
    become: true
    lineinfile:
      dest: /etc/php/7.1/fpm/php.ini
      regexp: "^extension=yaml.so"
      line: "extension=yaml.so"
      state: present

  - name: PHP - Add apc.shm_size=64M to php.ini
    become: true
    lineinfile:
      dest: /etc/php/7.1/fpm/php.ini
      regexp: "^apc.shm_size=64M"
      line: "apc.shm_size=64M"
      state: present

  - name: PHP - Restart
    become: true
    service:
      name: php7.1-fpm
      state: restarted

  - name: GRAV - Download Grav
    become: true
    unarchive:
      src: https://getgrav.org/download/core/grav-admin/latest
      dest: /tmp
      remote_src: True

  - name: GRAV - Delete webroot
    become: true
    file:
      path: /var/www/html
      state: absent

  - name: GRAV - Create webroot
    become: true
    file:
      path: /var/www/html
      state: directory

  - name: GRAV - Install Grav to webroot
    become: true
    shell: mv /tmp/grav-admin/* /var/www/html/.

  - name: GRAV - Delete grav-admin tmp directory
    become: true
    file:
      path: /tmp/grav-admin
      state: absent

  - name: GRAV - Copy nginx.conf
    become: true
    copy:
      src: etc/nginx/nginx.conf
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: 0644
      backup: yes

  - name: GRAV - Copy {{ domain }} sites-available configuration
    become: true
    template:
      src: etc/nginx/sites-available/default.j2
      dest: /etc/nginx/sites-available/{{ domain }}
      owner: root
      group: root
      mode: 0644
      backup: true

  - name: GRAV - Link sites-enabled configuration
    become: true
    file:
      state: link
      src: /etc/nginx/sites-available/{{ domain }}
      dest: /etc/nginx/sites-enabled/{{ domain }}
      force: yes

  - name: GRAV - Unlink default configuration
    become: true
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent

  - name: GRAV - Set permissions on webroot (1/2)
    become: true
    file:
      path: /var/www/html
      owner: www-data
      group: www-data
      recurse: yes

  - name: GRAV - Set permissions on webroot (2/2)
    become: true
    shell: |
      find /var/www/html -type f | xargs chmod 664
      find /var/www/html/bin -type f | xargs chmod 775
      find /var/www/html -type d | xargs chmod 775
      find /var/www/html -type d | xargs chmod +s
      umask 0002

  - name: GRAV - Start NGINX
    become: true
    service:
      name: nginx
      state: restarted
