--- 
- 
  gather_facts: false
  hosts: all
  remote_user: root
  tasks: 
    - 
      apt: 
        upgrade: true
      become: true
      name: "Update and upgrade apt packages"
    - 
      apt: 
        allow_unauthenticated: true
        name: php
        state: present
      name: "Install PHP"
    - 
      apt: 
        allow_unauthenticated: true
        name: apache2
        state: present
      name: "Install Apache2"
    - 
      file: 
        path: /var/www/html/grav
        recurse: true
        state: directory
      name: "Create /var/www/html/grav"
    - 
      name: "Unarchive a file that needs to be downloaded (added in 2.0)"
      unarchive: 
        dest: /var/www/html/grav
        remote_src: true
        src: "https://getgrav.org/download/core/grav-admin/1.4.2"
